/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_ClientJni */

#ifndef _Included_com_example_hellojni_ClientJni
#define _Included_com_example_hellojni_ClientJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_ClientJni
 * Method:    AddInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_hellojni_ClientJni_AddInt
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
